Product.create!(
 name: 'コウペンちゃん',
 price: 5000,
 description: 'なんでも肯定するよ' ,
 address_id: 1,
 brand_id: 1,
 postage_id: 1,
 shipping_method_id: 1,
 shipping_date_id: 1,
 condition_id: 1,
 size_id: 1,
 category_id: 219,
 user_id: 1,
)
Product.create!(
 name: 'コウペンちゃん',
 price: 5000,
 description: 'なんでも肯定するよ' ,
 address_id: 1,
 brand_id: 1,
 postage_id: 1,
 shipping_method_id: 1,
 shipping_date_id: 1,
 condition_id: 1,
 size_id: 1,
 category_id: 872,
 user_id: 1,
)
Product.create!(
 name: 'コウペンちゃん',
 price: 5000,
 description: 'なんでも肯定するよ' ,
 address_id: 1,
 brand_id: 1,
 postage_id: 1,
 shipping_method_id: 1,
 shipping_date_id: 1,
 condition_id: 1,
 size_id: 1,
 category_id: 1,
 user_id: 1,
)
Product.create!(
 name: 'コウペンちゃん',
 price: 5000,
 description: 'なんでも肯定するよ' ,
 address_id: 1,
 brand_id: 1,
 postage_id: 1,
 shipping_method_id: 1,
 shipping_date_id: 1,
 condition_id: 1,
 size_id: 1,
 category_id: 219,
 user_id: 1,
)
Product.create!(
 name: 'コウペンちゃん',
 price: 5000,
 description: 'なんでも肯定するよ' ,
 address_id: 1,
 brand_id: 1,
 postage_id: 1,
 shipping_method_id: 1,
 shipping_date_id: 1,
 condition_id: 1,
 size_id: 1,
 category_id: 872,
 user_id: 1,
)
Product.create!(
 name: 'コウペンちゃん',
 price: 5000,
 description: 'なんでも肯定するよ' ,
 address_id: 1,
 brand_id: 1,
 postage_id: 1,
 shipping_method_id: 1,
 shipping_date_id: 1,
 condition_id: 1,
 size_id: 1,
 category_id: 1,
 user_id: 1,
)
Product.create!(
 name: 'コウペンちゃん',
 price: 5000,
 description: 'なんでも肯定するよ' ,
 address_id: 1,
 brand_id: 1,
 postage_id: 1,
 shipping_method_id: 1,
 shipping_date_id: 1,
 condition_id: 1,
 size_id: 1,
 category_id: 219,
 user_id: 1,
)
Product.create!(
 name: 'コウペンちゃん',
 price: 5000,
 description: 'なんでも肯定するよ' ,
 address_id: 1,
 brand_id: 1,
 postage_id: 1,
 shipping_method_id: 1,
 shipping_date_id: 1,
 condition_id: 1,
 size_id: 1,
 category_id: 872,
 user_id: 1,
)
Product.create!(
 name: 'コウペンちゃん',
 price: 5000,
 description: 'なんでも肯定するよ' ,
 address_id: 1,
 brand_id: 1,
 postage_id: 1,
 shipping_method_id: 1,
 shipping_date_id: 1,
 condition_id: 1,
 size_id: 1,
 category_id: 1,
 user_id: 1,
)
Product.create!(
 name: 'コウペンちゃん',
 price: 5000,
 description: 'なんでも肯定するよ' ,
 address_id: 1,
 brand_id: 1,
 postage_id: 1,
 shipping_method_id: 1,
 shipping_date_id: 1,
 condition_id: 1,
 size_id: 1,
 category_id: 219,
 user_id: 1,
)
Product.create!(
 name: 'コウペンちゃん',
 price: 5000,
 description: 'なんでも肯定するよ' ,
 address_id: 1,
 brand_id: 1,
 postage_id: 1,
 shipping_method_id: 1,
 shipping_date_id: 1,
 condition_id: 1,
 size_id: 1,
 category_id: 872,
 user_id: 1,
)
Product.create!(
 name: 'コウペンちゃん',
 price: 5000,
 description: 'なんでも肯定するよ' ,
 address_id: 1,
 brand_id: 1,
 postage_id: 1,
 shipping_method_id: 1,
 shipping_date_id: 1,
 condition_id: 1,
 size_id: 1,
 category_id: 1,
 user_id: 1,
)